apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: nyuryoku-post
spec:
  createingress: false
  functionref:
    functionweights: null
    name: nyuryoku
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /nyuryoku
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /nyuryoku